import json
import subprocess
import sys
from pathlib import Path

from solvent.characterize import characterize_brains, generate_menu_data, validate_menu
from solvent.delivery.menu import DeliveryMenu


def test_validate_menu_reports_all_constraints() -> None:
    validation = validate_menu()

    assert validation.valid
    assert validation.checks == {
        "schema": True,
        "calibration_provenance": True,
        "monotone_difficulty": True,
        "non_dominated_tool_frontier": True,
        "deterministic_resolve": True,
    }
    assert "floor_ceiling_flags" not in validation.to_dict()


def test_validate_menu_can_profile_dev_floor_ceiling_flags(tmp_path: Path) -> None:
    validation = validate_menu(
        seeds=[40],
        profile_configs=["stub:happy_path", "stub:procedure"],
        profile_trace_dir=tmp_path / "validate-profile",
    )

    assert validation.valid
    assert validation.checks["floor_ceiling_profiled"] is True
    assert validation.profile_seeds == [40]
    assert validation.profile_configs == ["stub:happy_path", "stub:procedure"]
    assert validation.floor_ceiling_flags is not None
    assert "stub:happy_path:delivery_ceiling" in validation.floor_ceiling_flags


def test_generate_menu_data_records_characterization_metadata(tmp_path: Path) -> None:
    data = generate_menu_data([40, 41], profile_trace_dir=tmp_path / "profile")
    menu = DeliveryMenu.from_json(json.dumps(data))

    assert menu.source == "characterized"
    assert menu.calibration["seeds"] == [40, 41]
    assert "generated by solvent characterize" in menu.calibration["basis"]
    assert data["characterization"]["seeds"] == [40, 41]
    assert data["characterization"]["constraints"]["schema"] is True
    assert data["characterization"]["profile_configs"] == ["stub:happy_path", "stub:procedure"]
    assert "stub:happy_path" in data["brain_profiles"]
    assert data["brain_profiles"]["stub:happy_path"]["net_revenue"]["n"] == 2
    assert data["brain_profiles"]["stub:happy_path"]["support_conceded_value"]["n"] == 2
    assert data["brain_profiles"]["stub:happy_path"]["coherence_penalty"]["n"] == 2


def test_characterize_brains_runs_scorecard_profiles(tmp_path: Path) -> None:
    profiles = characterize_brains([42], ["stub:happy_path", "stub:procedure"], trace_dir=tmp_path / "profile")
    assert profiles["stub:happy_path"]["delivery_pass_rate"]["mean"] == 1.0
    assert profiles["stub:happy_path"]["coherence_penalty"]["n"] == 1
    assert profiles["stub:procedure"]["fraction_of_omniscient_optimal"]["n"] == 1


def test_cli_characterize_generate_menu_writes_artifact(tmp_path: Path) -> None:
    output = tmp_path / "menu.json"
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "solvent.cli.main",
            "characterize",
            "--generate-menu",
            "--seeds",
            "dev",
            "--output",
            str(output),
        ],
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0
    data = json.loads(output.read_text(encoding="utf-8"))
    assert data["source"] == "characterized"
    assert data["characterization"]["seeds"] == [40, 41, 42, 43, 44]
    assert data["brain_profiles"]["stub:happy_path"]["net_revenue"]["n"] == 5


def test_cli_characterize_validate_menu_profiles_seed_split(tmp_path: Path) -> None:
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "solvent.cli.main",
            "characterize",
            "--validate-menu",
            "--seeds",
            "dev",
            "--profile-configs",
            "stub:happy_path,stub:procedure",
            "--output",
            str(tmp_path / "menu.json"),
            "--json",
        ],
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0
    payload = json.loads(result.stdout)
    assert payload["checks"]["floor_ceiling_profiled"] is True
    assert payload["profile_seeds"] == [40, 41, 42, 43, 44]
    assert "floor_ceiling_flags" in payload
