from __future__ import annotations

import json
from copy import deepcopy
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path
from typing import Any

from solvent.delivery.menu import DIFFICULTIES, DeliveryMenu
from solvent.demo import CompareOptions, run_compare_artifact, summary_to_dict


@dataclass(frozen=True)
class MenuValidation:
    valid: bool
    version: str
    checksum: str
    checks: dict[str, bool]
    profile_seeds: list[int] | None = None
    profile_configs: list[str] | None = None
    floor_ceiling_flags: list[str] | None = None

    def to_dict(self) -> dict[str, Any]:
        payload = {
            "valid": self.valid,
            "version": self.version,
            "checksum": self.checksum,
            "checks": self.checks,
        }
        if self.profile_seeds is not None:
            payload["profile_seeds"] = self.profile_seeds
        if self.profile_configs is not None:
            payload["profile_configs"] = self.profile_configs
        if self.floor_ceiling_flags is not None:
            payload["floor_ceiling_flags"] = self.floor_ceiling_flags
        return payload


def validate_menu(
    menu: DeliveryMenu | None = None,
    seeds: list[int] | None = None,
    profile_configs: list[str] | None = None,
    profile_trace_dir: Path | None = None,
) -> MenuValidation:
    menu = menu or DeliveryMenu.load_default()
    profile_configs = profile_configs or ["stub:happy_path", "stub:procedure"]
    profiles = characterize_brains(seeds, profile_configs, trace_dir=profile_trace_dir) if seeds else {}
    floor_ceiling_flags = _floor_ceiling_flags(profiles) if seeds is not None else None
    checks = {
        "schema": menu.schema_version == "solvent_delivery_menu_v0_4",
        "calibration_provenance": _calibration_provenance(menu),
        "monotone_difficulty": _monotone_difficulty(menu),
        "non_dominated_tool_frontier": _non_dominated_tool_frontier(menu),
        "deterministic_resolve": _deterministic_resolve(menu),
    }
    if seeds is not None:
        checks["floor_ceiling_profiled"] = bool(profiles) if seeds else True
    return MenuValidation(
        valid=all(checks.values()),
        version=menu.version,
        checksum=menu.checksum,
        checks=checks,
        profile_seeds=list(seeds) if seeds is not None else None,
        profile_configs=profile_configs if seeds is not None else None,
        floor_ceiling_flags=floor_ceiling_flags,
    )


def generate_menu_data(
    seeds: list[int],
    menu: DeliveryMenu | None = None,
    profile_configs: list[str] | None = None,
    profile_trace_dir: Path | None = None,
) -> dict[str, Any]:
    menu = menu or DeliveryMenu.load_default()
    profile_configs = profile_configs or ["stub:happy_path", "stub:procedure"]
    data = deepcopy(menu.data)
    profiles = characterize_brains(seeds, profile_configs, trace_dir=profile_trace_dir) if seeds else {}
    data["source"] = "characterized"
    data["calibration"] = {
        "basis": "generated by solvent characterize from the recorded dev calibration/profile procedure",
        "seeds": list(seeds),
        "profile_configs": profile_configs,
        "constraints": ["monotone_difficulty", "non_dominated_tool_frontier", "magnitude_calibration", "discriminating_power"],
        "notes": "Delivery profile values are emitted in the frozen menu schema; brain profiles are recorded separately for realizable-reference analysis.",
    }
    data["characterization"] = {
        "procedure": "calibrated_synthetic_replay",
        "seeds": list(seeds),
        "profile_configs": profile_configs,
        "constraints": validate_menu(menu).checks,
        "floor_ceiling_flags": _floor_ceiling_flags(profiles),
    }
    data["brain_profiles"] = profiles
    return data


def characterize_brains(seeds: list[int], profile_configs: list[str], trace_dir: Path | None = None) -> dict[str, Any]:
    if not seeds or not profile_configs:
        return {}
    if len(profile_configs) == 1:
        profile_configs = [profile_configs[0], profile_configs[0]]
    artifact = run_compare_artifact(
        CompareOptions(
            config_a=profile_configs[0],
            config_b=profile_configs[1],
            seeds=seeds,
            trace_dir=trace_dir or Path("runs/characterize/profile"),
            redteam_paired=False,
            seed_split="dev",
        )
    )
    profiles = {config_id: dict(summary_to_dict(summary)) for config_id, summary in artifact.summaries.items()}
    if len(set(profile_configs)) == 1:
        return {profile_configs[0]: profiles[profile_configs[0]]}
    return profiles


def write_generated_menu(
    output: Path,
    seeds: list[int] | None = None,
    menu: DeliveryMenu | None = None,
    profile_configs: list[str] | None = None,
) -> None:
    data = generate_menu_data(seeds or [], menu, profile_configs, profile_trace_dir=output.parent / "profile")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(data, sort_keys=True, indent=2) + "\n", encoding="utf-8")


def _monotone_difficulty(menu: DeliveryMenu) -> bool:
    for task_type in menu.data["profile"]:
        for model in menu.public_models():
            pass_rates = [menu.pass_prob(task_type, model.name, difficulty) for difficulty in DIFFICULTIES]
            durations = [menu.duration(task_type, model.name, difficulty) for difficulty in DIFFICULTIES]
            if pass_rates != sorted(pass_rates, reverse=True) or durations != sorted(durations):
                return False
    return True


def _calibration_provenance(menu: DeliveryMenu) -> bool:
    return menu.source in {"calibrated_synthetic", "characterized"} and bool(menu.calibration.get("basis"))


def _non_dominated_tool_frontier(menu: DeliveryMenu) -> bool:
    models = menu.public_models()
    for target in models:
        for challenger in models:
            if challenger.name == target.name:
                continue
            if _dominates(menu, challenger.name, target.name):
                return False
    return True


def _dominates(menu: DeliveryMenu, challenger: str, target: str) -> bool:
    challenger_model = menu.model(challenger)
    target_model = menu.model(target)
    if challenger_model.price > target_model.price:
        return False
    strictly_better = challenger_model.price < target_model.price
    for task_type in menu.data["profile"]:
        for difficulty in DIFFICULTIES:
            challenger_pass = Decimal(str(menu.pass_prob(task_type, challenger, difficulty)))
            target_pass = Decimal(str(menu.pass_prob(task_type, target, difficulty)))
            challenger_duration = menu.duration(task_type, challenger, difficulty)
            target_duration = menu.duration(task_type, target, difficulty)
            if challenger_pass < target_pass or challenger_duration > target_duration:
                return False
            strictly_better = strictly_better or challenger_pass > target_pass or challenger_duration < target_duration
    return strictly_better


def _deterministic_resolve(menu: DeliveryMenu) -> bool:
    for model in menu.public_models():
        first = menu.resolve("data_clean", model.name, "easy", f"determinism:{model.name}")
        second = menu.resolve("data_clean", model.name, "easy", f"determinism:{model.name}")
        if first != second:
            return False
    return True


def _floor_ceiling_flags(profiles: dict[str, Any]) -> list[str]:
    flags = []
    for config_id, profile in profiles.items():
        delivery = profile.get("delivery_pass_rate", {})
        mean = delivery.get("mean") if isinstance(delivery, dict) else None
        if mean == 0:
            flags.append(f"{config_id}:delivery_floor")
        elif mean == 1:
            flags.append(f"{config_id}:delivery_ceiling")
    return flags
